<?php

/**
 * @file
 * Allows to choose Nodes based on the menu structure.
 */

/**
 * Implements hook_field_widget_info().
 */
function node_reference_menu_widget_field_widget_info() {
  return array(
    'node_reference_menu' => array(
      'label' => t('Menu select'),
      'field types' => array('node_reference'),
    ),
  );
}

/**
 * Implements hook_field_settings_form().
 */
function node_reference_menu_widget_field_settings_form($field, $instance, $has_data) {
  dpm($field);
}

/**
 * Implements hook_field_widget_form().
 */
function node_reference_menu_widget_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  //dpm($form, "form");
  //dpm($form_state, "form_state");
  //dpm($field, "field");
  //dpm($instance, "instance");
  //dpm($langcode, "langcode");
  //dpm($items, "items");
  //dpm($delta, "delta");
  //dpm($element, "element");
}